---
language: python
cache: pip

matrix:
  include:
    - name: "Python 2.7"
      os: "linux"
      python: "2.7"
      env:
        - IS_PY2: "1"
        - PYTHON_BIN: "python"
    - name: "Python 3.5"
      os: "linux"
      python: "3.5"
      env:
        - IS_PY2: "0"
        - PYTHON_BIN: "python3"
    - name: "Python 3.6"
      os: "linux"
      python: "3.6"
      env:
        - IS_PY2: "0"
        - PYTHON_BIN: "python3"
    - name: "Python 3.7"
      os: "linux"
      dist: "xenial"
      python: "3.7"
      env:
        - IS_PY2: "0"
        - PYTHON_BIN: "python3"
    - name: "Python 3.8-dev"
      os: "linux"
      dist: "xenial"
      python: "3.8-dev"
      env:
        - IS_PY2: "0"
        - PYTHON_BIN: "python3"

install:
  - $PYTHON_BIN -m pip install -U setuptools pip
  - $PYTHON_BIN -m pip install -e .[dev]

script:
  - $PYTHON_BIN -m pytest
...
# vim:st=2 sts=2 sw=2:
